### ISSUE TITLE
Local/Smoke volume is not rendered

### ISSUE THREAD

**Issue by OlegDzhuraev** [mseonKim/URP-VolumetricFog-ForwardPlus#1]
Hi! I've setup all according to readme (fog config, forward+ renderer, render feature), and global fog works fine.

But any placed **LocalVolumetricFog** or **SmokeVolume** has no any effect:
![pic](https://github.com/mseonKim/URP-VolumetricFog-ForwardPlus/assets/42075805/d7511f92-8e38-4c06-872a-9fadfc0d6d14)

I've tried different settings for fog and transform/collider size, but no result.

Am I missing something, or this is issue?

**Comment by mseonKim** [comment]
Hi, thanks for letting me know this. I tried to reproduce it and found that the smoke shader is not linked to the default local volume shader by default. Can you check if the shader is missing?

FYI, I fixed this issue and pushed the changeset to the main branch now.

![image](https://github.com/mseonKim/URP-VolumetricFog-ForwardPlus/assets/12474900/5ba4fbaa-e018-482b-a4b7-d0c44fd32093)

**Comment by OlegDzhuraev** [comment]
Yes, indeed, this parameter has not been set.

After downloading the new version, in the newly created config file the field is filled with **SmokeVolumeMaterial** and everything works correctly.

Thank you!
